name: linting
description: linting is a framework for creating custom linters using the analyzer_plugin and cli.
version: 1.2.1
repository: https://github.com/hisaichi5518/dart-linting/

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  analyzer: ^2.7.0
  analyzer_plugin: ^0.8.0
  freezed_annotation: ^0.14.3
  args: ^2.3.0
  path: ^1.8.0
  source_span: ^1.8.1
  glob: ^2.0.2
  yaml: ^3.1.0
  test: ^1.16.8

dev_dependencies:
  lints: ^1.0.1
  mocktail: ^0.2.0
